/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SongSongIdRouteImport } from './routes/song.$songId'
import { Route as ApiGenerateSongProgressRouteImport } from './routes/api.generate-song-progress'
import { Route as SongSongIdMockChatRouteImport } from './routes/song.$songId_.mock-chat'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SongSongIdRoute = SongSongIdRouteImport.update({
  id: '/song/$songId',
  path: '/song/$songId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateSongProgressRoute = ApiGenerateSongProgressRouteImport.update({
  id: '/api/generate-song-progress',
  path: '/api/generate-song-progress',
  getParentRoute: () => rootRouteImport,
} as any)
const SongSongIdMockChatRoute = SongSongIdMockChatRouteImport.update({
  id: '/song/$songId_/mock-chat',
  path: '/song/$songId/mock-chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/generate-song-progress': typeof ApiGenerateSongProgressRoute
  '/song/$songId': typeof SongSongIdRoute
  '/song/$songId/mock-chat': typeof SongSongIdMockChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/generate-song-progress': typeof ApiGenerateSongProgressRoute
  '/song/$songId': typeof SongSongIdRoute
  '/song/$songId/mock-chat': typeof SongSongIdMockChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/generate-song-progress': typeof ApiGenerateSongProgressRoute
  '/song/$songId': typeof SongSongIdRoute
  '/song/$songId_/mock-chat': typeof SongSongIdMockChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/generate-song-progress'
    | '/song/$songId'
    | '/song/$songId/mock-chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/generate-song-progress'
    | '/song/$songId'
    | '/song/$songId/mock-chat'
  id:
    | '__root__'
    | '/'
    | '/api/generate-song-progress'
    | '/song/$songId'
    | '/song/$songId_/mock-chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiGenerateSongProgressRoute: typeof ApiGenerateSongProgressRoute
  SongSongIdRoute: typeof SongSongIdRoute
  SongSongIdMockChatRoute: typeof SongSongIdMockChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/song/$songId': {
      id: '/song/$songId'
      path: '/song/$songId'
      fullPath: '/song/$songId'
      preLoaderRoute: typeof SongSongIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-song-progress': {
      id: '/api/generate-song-progress'
      path: '/api/generate-song-progress'
      fullPath: '/api/generate-song-progress'
      preLoaderRoute: typeof ApiGenerateSongProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/song/$songId_/mock-chat': {
      id: '/song/$songId_/mock-chat'
      path: '/song/$songId/mock-chat'
      fullPath: '/song/$songId/mock-chat'
      preLoaderRoute: typeof SongSongIdMockChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiGenerateSongProgressRoute: ApiGenerateSongProgressRoute,
  SongSongIdRoute: SongSongIdRoute,
  SongSongIdMockChatRoute: SongSongIdMockChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
